<?php

namespace App\Utils\Constants;

class FixedValuesConstants
{
    const STATUT_CANDIDATURE_EN_ATTENTE = "STATUT_CANDIDATURE_EN_ATTENTE";
    const STATUT_CANDIDATURE_TRAITER =  "STATUT_CANDIDATURE_TRAITER";
    const TYPE_AUTRE_INFORMATION = 'TYPE_AUTRE_INFORMATION';
}